name: Build and deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # 1. Переходим строго в папку проекта
            cd /home/dev-user/my-project
            
            # 2. Подтягиваем новый код
            git pull origin main
            
            # 3. Отключаем BuildKit (решает проблему старой версии buildx на твоем AWS)
            export DOCKER_BUILDKIT=0
            export COMPOSE_DOCKER_CLI_BUILD=0
            
            # 4. Перезапуск проекта
            # Используем sudo, если у dev-user нет прав на docker без него
            docker-compose down
            docker-compose up -d --build
            
            # 5. Очистка (исправил опечатку с -fname на -f)
            docker image prune -f