name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build

      - name: Deploy and Rebuild
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/dev-user/my-project
            git pull origin main  # Подтягиваем новый код
            docker-compose up -d --build  # Флаг --build заставит Docker пересобрать React-приложение
            docker image prune -f  # Удаляем старые ненужные образы, чтобы не забивать место
