name: Build and deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Deploy and Rebuild via SSH 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/dev-user/my-project
            # Если папки еще нет или это не git-репозиторий — клонируем
            if [ ! -d ".git" ]; then
              git clone https://github.com/vmelniki2828/test_joke.git .
            else
              git pull origin main
            fi
            # Собираем образ и перезапускаем контейнеры
            docker-compose up -d --build
            # Удаляем старые слои, чтобы диск не переполнился
            docker image prune -f